name: Build ZMK Firmware (roBa)

on:
  workflow_dispatch:
  push:
    paths:
      - "config/**"
      - "boards/**"

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      build-matrix: |
        [
          { "board": "nice_nano_v2", "shield": "roBa" }
        ]
      # 任意: 生成物の名前を分かりやすくしたい場合
      # archive-name: "firmware-roBa-nicenano"
